### ISSUE TITLE
Questions not rendering completely

### ISSUE THREAD

**Issue by aaronburmeister** [learn-co-curriculum/programming-univbasics-nds-final-quiz#10]
![image](https://user-images.githubusercontent.com/48975739/71425134-6408b280-2667-11ea-98c8-a9274afde385.png)

Here's questions 7 and 8, which look identical. Many of the questions aren't showing up completely. I figured I'd check the github, but the questions seem to be intact in the README. I'm using Chrome 79.0.3945.88 (Official build) (64-bit).

**Comment by maxwellbenton** [comment]
Hi @aaronburmeister,

Thank you for reporting this issue.  We've updated this quiz after identifying a conflict with our quiz parser, changing questions 7 and 8 and fixing the missing content on questions 2 and 9, which should resolve this issue.

Thank you for contributing to a Learn lesson!
