### ISSUE TITLE
Test is super wonky 

### ISSUE THREAD

**Issue by DHarrisonG** [learn-co-curriculum/programming-univbasics-nds-final-quiz#11]
7 and 8 are the exact same question but have separate answers 

question 9 isn't even a finished question

**Comment by maxwellbenton** [comment]
Hi @DHarrisonG,

Thank you for reporting this issue.  We've updated this quiz, changing questions 7 and 8 and fixing the missing content on question 9. 

Thank you for contributing to a Learn lesson!
