### ISSUE TITLE
Duplicate Question

### ISSUE THREAD

**Issue by elzbyfar** [learn-co-curriculum/programming-univbasics-nds-final-quiz#12]
The **Nested Data Structure Transformation Quiz** has a question that appears twice in the quiz. Questions 7 & 8:

> 7. We're preparing to code a looping algorithm to collect all the :margins.
> 
> results[:winners][1][:margin]
> results[:winners][-1][:margin]
> results[:winners][2][:margin]
> results[:winners].first[:margin]
> 
> 8. We're preparing to code a looping algorithm to collect all the :margins.
> 
> results[:winners][1][:margin]
> results[:winners][-1][:margin]
> results[:winners][2][:margin]
> results[:winners].first[:margin]

Somehow the answers were different.

**Comment by elzbyfar** [comment]
<img width="1056" alt="Screenshot 2020-01-13 at 12 28 33 PM" src="https://user-images.githubusercontent.com/50682184/72277848-b4d55080-3600-11ea-95ab-69adde64ae9c.png">

**Comment by mav-code** [comment]
Question 9 also seems to have become messed up during revision, unless I'm failing to understand it

**Comment by maxwellbenton** [comment]
Hi @elzbyfar and @mav-code,

We've updated this quiz and corrected the duplicate questions as well as question 9's missing content. Thank you both for providing this feedback and contributing to a Learn lesson!
