### ISSUE TITLE
Questions 7 and 8 are identical but require different answers

### ISSUE THREAD

**Issue by hoyzington** [learn-co-curriculum/programming-univbasics-nds-final-quiz#4]

**Comment by maxwellbenton** [comment]
Hi @hoyzington,

Thank you for opening this issue. While questions 7 and 8 do look very similar at first, question 7 is asking for the _first_ winning horse's margin, but question 8 is asking for the _last_ winning horse's margin. We've added emphasis to the two questions to avoid this confusion going forward.

Thank you for contributing!
