### ISSUE TITLE
There is two timees the same question

### ISSUE THREAD

**Issue by Santosian** [learn-co-curriculum/programming-univbasics-nds-final-quiz#5]
The question number 7 and 8 are exactly the same. When i select for the send time the first answer, wich is correct, it tells me it is wrong.

**Comment by maxwellbenton** [comment]
Hi @aaronburmeister,

Thank you for reporting this issue.  We've updated this quiz after identifying a conflict with our quiz parser, changing questions 7 and 8 so that they ask different questions and fixing missing content on questions 2 and 9.

Thank you for contributing to a Learn lesson!
