### ISSUE TITLE
Nested Data Structure Transformation Quiz - questions 7-9 need improvement

### ISSUE THREAD

**Issue by asengelhart** [learn-co-curriculum/programming-univbasics-nds-final-quiz#6]
Questions 7 and 8 are identical, and don't provide enough information to know what the question is actually asking about.

![image](https://user-images.githubusercontent.com/31832454/69933250-5195c180-148b-11ea-8bef-f6cc03c4116d.png)

Question 9 is a sentence fragment, with no way of knowing what is actually being asked about.

![image](https://user-images.githubusercontent.com/31832454/69933382-bcdf9380-148b-11ea-8171-0fc0099d698d.png)

**Comment by maxwellbenton** [comment]
Hi @asengelhart,

Thank you for reporting this issue.  We've updated this quiz after identifying a conflict with our quiz parser, changing questions 7 and 8 and fixing missing content on questions 2 and 9.

Thank you for contributing to a Learn lesson!
