### ISSUE TITLE
Same question different answers

### ISSUE THREAD

**Issue by theoluyi** [learn-co-curriculum/programming-univbasics-nds-final-quiz#7]
How does this make sense?

<img width="1280" alt="Screen Shot 2019-12-05 at 2 13 33 PM" src="https://user-images.githubusercontent.com/56609975/70265973-89da2000-1769-11ea-8d15-14a34c913219.png">

**Comment by maxwellbenton** [comment]
Hi @theoluyi,

Thank you for reporting this issue.  We've updated this quiz after identifying a conflict with our quiz parser, changing questions 7 and 8 and fixing the missing content on questions 2 and 9, which should resolve this issue.

Thank you for contributing to a Learn lesson!
