### ISSUE TITLE
Questions Title/Answer Issue

### ISSUE THREAD

**Issue by fishcereal** [learn-co-curriculum/programming-univbasics-nds-final-quiz#8]
- Question 2 asks 'Taking into consideration both the previous hash of horse information'. There is only 1 hash of horse information if referring to the 'results' hash, or three hashes of horse information if referring to the 'winners' array of horse hashes. Either way, 'both the previous hash of horse information' should be changed. 

- Questions 7 and 8 are the same question with the same possible answers: 
"
We're preparing to code a looping algorithm to collect all the :margins.

results[:winners][1][:margin]
results[:winners][-1][:margin]
results[:winners][2][:margin]
results[:winners].first[:margin]
"
None of the answers allude to looping through the code to collect all the margins. Each answer would only return one margin. 

Each question has different correct answers: 7's answer is B and 8's answer is D.

**Comment by maxwellbenton** [comment]
Hi @fishcereal,

Thank you for reporting this issue and providing detailed feedback.  We've updated this quiz after identifying a conflict with our quiz parser, changing questions 7 and 8 and updated question 2 for clarity, which should resolve this issue going forward.

Thank you for contributing to a Learn lesson!
