### ISSUE TITLE
Duplicate Quiz Questions

### ISSUE THREAD

**Issue by d-otis** [learn-co-curriculum/programming-univbasics-nds-final-quiz#9]
Questions #7 and #8 are duplicates.

**Comment by maxwellbenton** [comment]
Hi @d-otis,

Thank you for reporting this issue.  We've updated this quiz after identifying a conflict with our quiz parser, changing questions 7 and 8 and fixing the missing content on questions 2 and 9, which should resolve this issue.

Thank you for contributing to a Learn lesson!
